version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: crypto-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crypto-network

    
  etl:
    build: .
    container_name: crypto-etl
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres", "5432", "--", "python", "src/main.py"]
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
    networks:
      - crypto-network


volumes:
  postgres_data:

networks:
  crypto-network:
    driver: bridge
